// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRh3uXiwlXDyRDuLdntilBD2CEDixK508',
    appId: '1:380623468019:web:1309bf67e8aa6fb1ad8e86',
    messagingSenderId: '380623468019',
    projectId: 'fiwi-7c575',
    authDomain: 'fiwi-7c575.firebaseapp.com',
    storageBucket: 'fiwi-7c575.appspot.com',
    measurementId: 'G-NK7DXZE8RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKEIqWHTk3glxE-GDUIf0W2mzvhvbygxs',
    appId: '1:380623468019:android:498e52bdd7e3efaaad8e86',
    messagingSenderId: '380623468019',
    projectId: 'fiwi-7c575',
    storageBucket: 'fiwi-7c575.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtjd3mUji9-sLivj0dLzE5cjs53e-BTg4',
    appId: '1:380623468019:ios:c1c2adf626a87765ad8e86',
    messagingSenderId: '380623468019',
    projectId: 'fiwi-7c575',
    storageBucket: 'fiwi-7c575.appspot.com',
    iosClientId: '380623468019-97p2p0a775va18imk31fu33557c6trtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiwi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtjd3mUji9-sLivj0dLzE5cjs53e-BTg4',
    appId: '1:380623468019:ios:c1c2adf626a87765ad8e86',
    messagingSenderId: '380623468019',
    projectId: 'fiwi-7c575',
    storageBucket: 'fiwi-7c575.appspot.com',
    iosClientId: '380623468019-97p2p0a775va18imk31fu33557c6trtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiwi',
  );
}
